name: Replace install.wim in Windows ISO

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

jobs:
  replace-install-wim:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y p7zip-full aria2 wimtools chntpw genisoimage curl

    - name: Download Windows 10 22H2 German ISO using UUP dump
      run: |
        git clone https://github.com/uup-dump/uup-dump.git
        cd uup-dump
        chmod +x uup_download_linux.sh
        ./uup_download_linux.sh --lang de-de --edition professional --releaseid 22H2 --arch x64 --virtualedition enterprise --autodownload
        
    - name: Download Windows 11 24H2 German ISO
      run: |
        curl -L -o MediaCreationTool.exe https://go.microsoft.com/fwlink/?linkid=2156295
        chmod +x MediaCreationTool.exe
        ./MediaCreationTool.exe /Eula Accept /Retail /MediaLangCode de-DE /Edition Windows11 /MediaArch x64 /Download /Quiet

    - name: Extract ISOs using 7zip
      run: |
        7z x Win10.iso -oWin10
        7z x Win11.iso -oWin11

    - name: Replace install.wim from Win11 to Win10
      run: |
        cp Win11/sources/install.wim Win10/sources/install.wim

    - name: Create new ISO with replaced install.wim
      run: |
        genisoimage \
          -o Windows10_Modified.iso \
          -b boot/etfsboot.com \
          -no-emul-boot \
          -allow-limited-size \
          -iso-level 3 \
          -boot-load-size 4 \
          -boot-info-table \
          -R -J Win10

    - name: Upload new ISO as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows10_Modified.iso
        path: Windows10_Modified.iso

    - name: Get current date as tag
      id: get_date
      run: echo "tag_name=$(date +'%d.%m.%Y')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.tag_name }}"
        release_name: "Windows 10 Modified - ${{ env.tag_name }}"
        body: "This release contains the modified Windows 10 ISO with the install.wim from Windows 11."
        draft: false
        prerelease: false

    - name: Upload ISO to GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: Windows10_Modified.iso
