name: Replace install.wim in Windows ISO

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

jobs:
  replace-install-wim:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y p7zip-full genisoimage curl

    - name: Download Windows 10 ISO
      run: |
        curl -L -o Win10.iso "https://securedl.cdn.chip.de/downloads/35017006/Win10_22H2_German_x64.iso?cdr=4&cid=81515537&platform=chip&1744611672-1744619172-76c26b-B-f2db84e3c5ddc7a9549042bea9cf2d7f"
        7z t Win10.iso || (echo "Win10 ISO is corrupted" && exit 1)

    - name: Download Windows 11 ISO
      run: |
        curl -L -o Win11.iso "https://securedl.cdn.chip.de/downloads/126531758/Win11_24H2_German_x64.iso?cdr=4&cid=183880484&platform=chip&1744611764-1744619264-cb0667-B-f5034996676a42cf29c12765501828e5"
        7z t Win11.iso || (echo "Win11 ISO is corrupted" && exit 1)

    - name: Extract ISOs using 7zip
      run: |
        7z x Win10.iso -oWin10
        7z x Win11.iso -oWin11

    - name: Replace install.wim from Win11 to Win10
      run: |
        cp Win11/sources/install.wim Win10/sources/install.wim

    - name: Create new ISO with replaced install.wim
      run: |
        genisoimage \
          -o Windows10_Modified.iso \
          -b boot/etfsboot.com \
          -no-emul-boot \
          -allow-limited-size \
          -iso-level 3 \
          -boot-load-size 4 \
          -boot-info-table \
          -R -J Win10

    - name: Upload new ISO as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows10_Modified.iso
        path: Windows10_Modified.iso

    - name: Get current date as tag
      id: get_date
      run: echo "tag_name=$(date +'%d.%m.%Y')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.tag_name }}"
        release_name: "Windows 10 Modified - ${{ env.tag_name }}"
        body: "This release contains the modified Windows 10 ISO with the install.wim from Windows 11."
        draft: false
        prerelease: false

    - name: Upload ISO to GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: Windows10_Modified.iso
